# Generated by Django 2.1.4 on 2018-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255, verbose_name='名称')),
                ('urls', models.CharField(default=None, max_length=255, verbose_name='链接')),
            ],
        ),
    ]
