# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=255, verbose_name='用户名')),
                ('passwd', models.CharField(default='e10adc3949ba59abbe56e057f20f883e', max_length=255, verbose_name='密码')),
                ('position', models.CharField(default=None, max_length=255, verbose_name='职位')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
