# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-10 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='email_address',
            field=models.CharField(default=None, max_length=255, verbose_name='邮箱地址'),
        ),
    ]
