# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tb_user_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_resetpwd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default=None, verbose_name='用户ID')),
                ('onlyId', models.CharField(max_length=255, verbose_name='唯一标识')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
