# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tb_resetpwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_registry_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default=None, verbose_name='邀请者ID')),
                ('registry_code', models.IntegerField(default=None, verbose_name='用户ID')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
