# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tb_registry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='inviteId',
            field=models.IntegerField(default=0, verbose_name='邀请人ID'),
        ),
    ]
