# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='session',
        ),
    ]
