# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(default=None, max_length=255, verbose_name='sessionId')),
                ('expire_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
