# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='userId',
            field=models.IntegerField(default=None, verbose_name='userId'),
        ),
    ]
