# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_session_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='tb_user',
            name='sex',
            field=models.IntegerField(default=0, verbose_name='性别'),
        ),
    ]
