# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
